# build environment
FROM node:12.13.1-alpine as builder
WORKDIR /source
ENV PATH /source/node_modules/.bin:$PATH
COPY package.json /source/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent
COPY . /source
RUN npm run build

FROM nginx:1.17.6-alpine
COPY --from=builder /source/build /usr/share/nginx/html
COPY --from=builder /source/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

EXPOSE 80

COPY ./env.sh .
COPY .env .

RUN apk add --no-cache bash

RUN chmod +x env.sh

CMD ["/bin/bash", "-c", "/usr/share/nginx/html/env.sh && nginx -g \"daemon off;\""]

