version: '3.1'

services:
  webapp-prod:
    container_name: webapp-prod
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - NGINX_PORT=80
      - API_URL=http://64.137.180.153:5000/api/
      - FRONT_URL=http://64.137.180.153/
    networks:
      - network
networks:
  network:
    driver: bridge
